### ISSUE TITLE
win10 python3 error?

### ISSUE THREAD

**Issue by CxyCH** [rospypi/simple#10]
Hi:
  I install rosbag in win10 with "pip install --extra-index-url https://rospypi.github.io/simple rospy rosbag". It can be installed in win10, anaconda.
  Then when I use the command "import rosbag", I get the error "AttributeError: module 'socketserver' has no attribute 'ForkingMixIn'". 
  So I want to know this package can run in win10? 

  Thank you very much.

**Comment by timlukins** [comment]
I have this issue as well. Simply reproduced on a windows system (via a virtual env in which `pip install --extra-index-url https://rospypi.github.io/simple/ rospy` was run first):

```
>>> import rospy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\client.py", line 60, in <module>
    import rospy.impl.init
  File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\impl\init.py", line 49, in <module>
    import rosgraph.xmlrpc
  File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rosgraph\xmlrpc.py", line 133, in <module>
    class ForkingXMLRPCServer(socketserver.ForkingMixIn, SimpleXMLRPCServer):
AttributeError: module 'socketserver' has no attribute 'ForkingMixIn'
```

A quick google reveals this where `ForkingMixIn` method is NOT availabel on Windows: https://stackoverflow.com/questions/47074315/attributeerror-module-socketserver-has-no-attribute-forkingmixin

**Comment by CxyCH** [comment]
> I have this issue as well. Simply reproduced on a windows system (via a virtual env in which `pip install --extra-index-url https://rospypi.github.io/simple/ rospy` was run first):
> 
> ```
> >>> import rospy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\__init__.py", line 49, in <module>
>     from .client import spin, myargv, init_node, \
>   File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\client.py", line 60, in <module>
>     import rospy.impl.init
>   File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rospy\impl\init.py", line 49, in <module>
>     import rosgraph.xmlrpc
>   File "C:\Users\timlu\Code\github\neve\venv\lib\site-packages\rosgraph\xmlrpc.py", line 133, in <module>
>     class ForkingXMLRPCServer(socketserver.ForkingMixIn, SimpleXMLRPCServer):
> AttributeError: module 'socketserver' has no attribute 'ForkingMixIn'
> ```
> 
> A quick google reveals this where `ForkingMixIn` method is NOT availabel on Windows: https://stackoverflow.com/questions/47074315/attributeerror-module-socketserver-has-no-attribute-forkingmixin
> 
> EDIT: This may be related: [ros/ros_comm#1819](https://github.com/ros/ros_comm/pull/1819)
> 
> Really like the idea of using pure python to share/process rosbag data on non-ROS systems - so keep up the good work!

A simple solution is to use WSL.

**Comment by otamachan** [comment]
Hi, sorry for my late response.
I just release the newer version of [ros_comm](https://github.com/ros/ros_comm/tree/1.15.7), please try it.
Thanks.

**Comment by otamachan** [comment]
I will close this.
If you still have a problem, please reopen or create a new issue.
