### ISSUE TITLE
"No matching distribution found for sip<5.0.0 (from PyKDL->tf2_geometry_msgs)"

### ISSUE THREAD

**Issue by gavanderhoorn** [rospypi/simple#19]
On Windows 10, Python 3.8.3 `amd64`, I get the following error when trying to install `tf2_geometry_msgs`:

```
(venv_rospy38) C:\Users\user>pip install --extra-index-url https://rospypi.github.io/simple/ tf2_geometry_msgs
Looking in indexes: https://pypi.org/simple, https://rospypi.github.io/simple/
Collecting tf2_geometry_msgs
  Using cached https://github.com/rospypi/simple/raw/any/tf2-geometry-msgs/tf2_geometry_msgs-0.6.5.post0-py2.py3-none-any.whl (3.2 kB)
Requirement already satisfied: geometry-msgs in c:\users\user\venv_rospy38\lib\site-packages (from tf2_geometry_msgs) (1.13.0)
Collecting PyKDL
  Using cached https://github.com/rospypi/simple/raw/Windows_3.8/pykdl/PyKDL-1.4.post1-cp38-cp38-win_amd64.whl (295 kB)
Requirement already satisfied: tf2-ros in c:\users\user\venv_rospy38\lib\site-packages (from tf2_geometry_msgs) (0.6.5)
Requirement already satisfied: rospy in c:\users\user\venv_rospy38\lib\site-packages (from tf2_geometry_msgs) (1.15.7)
Requirement already satisfied: genpy<2000 in c:\users\user\venv_rospy38\lib\site-packages (from geometry-msgs->tf2_geometry_msgs) (0.6.12)
ERROR: Could not find a version that satisfies the requirement sip<5.0.0 (from PyKDL->tf2_geometry_msgs) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0)
ERROR: No matching distribution found for sip<5.0.0 (from PyKDL->tf2_geometry_msgs)
```

Trying `pip install "sip<5.0.0"` fails with a similar error.

Is this a Python 3.8 problem?

---

Edit: forgot to say: 💯 🍶 👍. This project has made running the odd Python publishers/subscribers/service server on a Windows machine so much more convenient.

**Comment by otamachan** [comment]
Thanks for your feedback.

The current PyKDL depends on the older SIP(4.19). It seems that the binary packages of SIP for Python 3.8 are not released from the pypi(https://pypi.org/project/sip/4.19.8/#files), so yes we cannot install `tf2_geometry_msgs` in any platofrom with Python 3.8.

PyKDL is now using pybind11 instead of SIP(https://github.com/orocos/orocos_kinematics_dynamics/pull/229) which is nice, but unfortunately it's not released yet.

**Comment by gavanderhoorn** [comment]
Ah, that makes sense.

Does #23 work towards using pybind11?

**Comment by otamachan** [comment]
> Does #23 work towards using pybind11?

Yes, with #24, I released pre release packages to https://rospypi.github.io/simple/_pre
So you can install `tf2_geometry_msgs` with Python 3.8 by
```bash
pip install --extra-index-url https://rospypi.github.io/simple/_pre tf2_geometry_msgs
```
I don't use Python 3.8 for now so I cannot test with 3.8.
If you have time, please try and test it.
If it looks ok, I will release them to https://rospypi.github.io/simple.

**Comment by gavanderhoorn** [comment]
Thanks :+1: 

This seems to install for my in a Python 3.8 `venv` on Linux (Ubuntu Xenial in this case, `amd64`).

I'll try Windows later.

**Comment by gavanderhoorn** [comment]
I'm going to close this as I don't believe I've run into this problem any more recently.

Thanks again for the awesome work here @otamachan :+1:
