### ISSUE TITLE
libpython ImportError when importing PyKDL in Python 3.7, 3.6 with Conda env

### ISSUE THREAD

**Issue by trevorablett** [rospypi/simple#29]
Thanks for setting this up! It's been super helpful to have lightweight ROS options.

I'm trying to install PyKDL in Conda environments using Python 3.7 and Python 3.6 with
```
pip install --extra-index-url https://rospypi.github.io/simple/_pre PyKDL
```
which runs fine, but then I get:
```
>>> import PyKDL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trevor/anaconda3/envs/py37-test/lib/python3.7/site-packages/PyKDL/__init__.py", line 1, in <module>
    from .PyKDL import *
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

I've found three ways to resolve this at the moment, but I don't think any of them actually address the issue:

1) Using a Conda environment with Python 3.8, the error doesn't occur. Might be related to https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build.
2) Modifying `LD_LIBRARY_PATH` to include `~/anaconda3/envs/py37-test/lib` before running any code.
3) Cloning the package and building from source with `python setup.py bdist_wheel`, then installing the wheel file with `pip install dist/PyKDL-1.4.post2-cp37-cp37m-linux_x86_64.whl`.

I'm not sure if this is possible to easily fix, or even worth fixing, but I figured for anyone else who's attempting to use Conda and python 3.6/3.7, it might be helpful to see their options.

**Comment by otamachan** [comment]
Thank you for your report.

In Python 3.6/3.7 built with `--enable-shared` it seems that distutils will build extensions with `libpython.so` . We build packages by `actions/setup-python` in github action and it offers only the Pythons with `--enable-shared` . That's the reason PyKDL library is linked to `libpython.so`.

I overwrite `Py_ENABLE_SHARED` before calling the build process to avoid linking `libpython.so` in #30 and newly built packages are now released to `https://rospypi.github.io/simple/_pre` .
Could you try `pip install --extra-index-url https://rospypi.github.io/simple/_pre PyKDL` again?

**Comment by trevorablett** [comment]
This appears to have solved it in. Thanks for the quick response! I'll close this now.
