### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found (when import tf2_ros)

### ISSUE THREAD

**Issue by tckarenchiang** [rospypi/simple#37]
On Windows 10, Python 3.7.6, amd64, after installing `tf2_ros` (`pip install --extra-index-url https://rospypi.github.io/simple/ tf2_ros`), I get the following error when trying to run `import  tf2_ros`
```

(venv) C:\>python -c "import tf2_ros"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\venv\lib\site-packages\tf2_ros\__init__.py", line 38, in <module>
    from tf2_py import *
  File "C:\venv\lib\site-packages\tf2_py\__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: DLL load failed: The specified module could not be found.

```
I didn't have this error on another laptop (with the same specs) so I'm puzzled why this error occurs.
Thanks!

**Comment by tckarenchiang** [comment]
I have uninstalled Python 3.7.6 and installed Python 3.8.5 and there is no such error anymore

**Comment by gavanderhoorn** [comment]
Could this be closed @tckarenchiang ?
