### ISSUE TITLE
tf2_sensor_msgs support

### ISSUE THREAD

**Issue by osholsonel20** [rospypi/simple#38]
Hey great asset to have, I'm currently installing the whl files onto our cluster for bag file processing.

How hard would it be to add the tf2_sensor_msgs to rospy simple?

**Comment by otamachan** [comment]
Thank you for your feedback.
I released `sensor_msgs` and `tf2_sensor_msgs` to https://rospypi.github.io/simple/_pre (#39)

Could you test 
```bash
pip install -U --extra-index-url https://rospypi.github.io/simple/_pre sensor_msgs tf2_sensor_msgs
```
?
If it's ok, I will release them to https://rospypi.github.io/simple.

**Comment by osholsonel20** [comment]
Sure, will do!

**Comment by osholsonel20** [comment]
Looks like it works for me! Thank you!
