### ISSUE TITLE
sensor_msgs: missing point_cloud2?

### ISSUE THREAD

**Issue by gavanderhoorn** [rospypi/simple#48]
On recent installs of `sensor_msgs`, it appears the [point_cloud2.py](https://github.com/ros/common_msgs/blob/20a833b56f9d7fd39655b8491a2ec1226d2639b3/sensor_msgs/src/sensor_msgs/point_cloud2.py) utility file is missing.

For feature parity with 'native' installs of `sensor_msgs`, it would be great if this could be added.

Is there a specific reason `point_cloud2.py` is not included in the `rospypi` distribution?

**Comment by otamachan** [comment]
Thank you for your feedback.
I think `point_cloud2.py` in the latest version was removed by some mistake.
I'll release the fixed version soon.
