### ISSUE TITLE
Generating messages (on Windows): '-r' or '-s'?

### ISSUE THREAD

**Issue by gavanderhoorn** [rospypi/simple#5]
While trying to follow the instructions for generating messages at the end of [the readme](https://github.com/rospypi/simple/blob/c073ff067ce4a004493ce8c83199ecc7f85318bb/README.md), I'm confused about the command lines shown.

The first example uses `-s`:

```
rospy-build genmsg your_package_path -s msgs/
```

the second example (commented, and right below it), uses `-r`:

```
# ex.rospy-build -g ros_tutorials/rospy_tutorials/ -r msgs/
```

`rospy-build` doesn't seem to accept `-r`, only `-s`. But `-s` is the "path to packages.yaml", which I don't have (or at least I believe I don't have it).

Could you perhaps clarify?

**Comment by otamachan** [comment]
Thank you for your feedback.
Sorry for confusing, but `-s` is correct and it's `message search root path` which is the root path where the generator tries to find the depending message files.

**Comment by gavanderhoorn** [comment]
Thanks.

This seems to work now. Even generates `.action`s.
