### ISSUE TITLE
How to open a rosbag stream

### ISSUE THREAD

**Issue by Janphr** [rospypi/simple#65]
Hey,

I have a rosbag as BytesIO and would like to make a Bag object out of it. 
In bag.py it says
```
        @param f: filename of bag to open or a stream to read from
        @type  f: str or file
```
which needs to satisfy `isinstance(f, io.IOBase)`, but when i pass the BytesIO object i get:
```
Traceback (most recent call last):
  File "/home/zft-jr19f/Zft/workspace/control-station/venv/lib/python3.8/site-packages/rosbag/bag.py", line 1433, in _open
    if 'b' not in self._file.mode and not isinstance('', bytes):
AttributeError: '_io.BytesIO' object has no attribute 'mode'
```
Minimal example would be:
```
from io import BytesIO
import rosbag

f = open("some_bag.bag", "rb")
data = BytesIO(f.read())
bag = rosbag.Bag(data)
```
What kind of object am I supposed to pass to rosbag.Bag() to make this work? Right now I'm saving the ByteIO object first and then read it in again via filename, 
```
with open(filename, "wb") as f:
    f.write(data.read())
bag = rosbag.Bag(filename)
```
which works, but I'd like to skip the file saving step.

Thanks!

**Comment by bonprosoft** [comment]
Hi, thank you for creating the issue.
However, I think this is not the best place to ask about rosbag.
Could you please create an issue at ros/ros_comm repository, where `rosbag` is developed?
https://github.com/ros/ros_comm/issues

ROS Discourse is also a good place to ask.
https://discourse.ros.org/

---

It seems you can use `BytesIO` as a underlying data stream of rosbag by faking `mode` field of the instance:

```py
from io import BytesIO
import rosbag

f = open("some_bag.bag", "rb")
data = BytesIO(f.read())
data.mode = "rb"  # Added
bag = rosbag.Bag(data)
```

But I'm not sure if this is the best solution.

**Comment by Janphr** [comment]
Hey, 
thanks for the quick reply.
Your solution seems to work, I guess that's good enough for me for now, thanks! :)
