### ISSUE TITLE
Windows Python 3 Error; fix available upstream?

### ISSUE THREAD

**Issue by jpaulos** [rospypi/simple#9]
When running with Python 3 and Windows 10, I encountered this previously-reported rospy error specific to Windows:

https://github.com/ros/ros_comm/pull/1819

I see the (small) fix was merged into ros/roscomm:melodic-devel on Jan 8, 2020, but it is not available in rospypi yet because simple/roslz4/ross_comm is tagged to d93fcae, which dates from Nov 16, 2019.

Would it be possible to advance the version, which I hope would solve this problem?

**Comment by otamachan** [comment]
Hi, sorry for my late response.
I just release the newer version of [ros_comm](https://github.com/ros/ros_comm/tree/1.15.7), please try it.
Thanks.

**Comment by jpaulos** [comment]
This new release fixes my problem. I suspect it also fixes #10 . Thanks!
